services:
  configserver:
    image: "dimk10/configserver:s6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  accounts:
    image: "dimk10/accounts:s6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/" # The first is a prefix the second corresponds to the image name
      SPRING_PROFILES_ACTIVE: default
  loans:
    image: "dimk10/loans:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/" # The first is a prefix the second corresponds to the image name
      SPRING_PROFILES_ACTIVE: default
  cards:
    image: "dimk10/cards:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/" # The first is a prefix the second corresponds to the image name
      SPRING_PROFILES_ACTIVE: default
networks:
  eazybank:
    driver: "bridge"
